### ISSUE TITLE
Update to Deta Space

### ISSUE THREAD

**Issue by heytorvas** [BogDAAAMN/deta-deploy-action#9]
Hey @BogDAAAMN! What's up?

First of all, thanks for development this Github Action. I started to use and now i can't stop haha.

I have a doubt related the future of this project. Deta announced few days ago about Deta Space and discontinue Deta Cloud (like a migration process). So, my question is, do you have some plans to upgrade and improve this action to deploy apps on the new environment?

**Comment by bogdaaamn** [comment]
Heyyyy @heytorvas, thanks for reaching out,

Unfortunately this Action should retire once Deta Cloud is out 😭 

Thought about upgrade it to fit into Space, but @mikBighne98 already created one to push and release projects to Space. Possibly check [neobrains/space-deployment-github-action](https://github.com/neobrains/space-deployment-github-action) and see if it fits your use case. Going forward I will contribute and use this one, instead of mainting a separate one. 

Also there is an ongoing conversation about it on the [Deta discord](https://go.deta.dev/discord) if you wanna give feedback there https://discord.com/channels/827546555200438332/1075793102058557461

**Comment by heytorvas** [comment]
Thanks for answer me, @BogDAAAMN. 

I'll make some tests with this suggested action and update my projects.

Have a good week!
